
    <div class="container"  id="id-page-container">
        <div class="jumbotron" style="color:#000">
            <div class="panel panel-default">
              <div class="panel-heading"><h3>Capture and share moments in the world</h3></div>
                <div class="panel-body">
                    <p>
                        Messenger is a <strong>fast</strong>, <strong>beautiful</strong> and <strong>fun</strong> way to share your life with friends and family.
                    </p>
                    <p>
                        Take a picture or video, choose a filter to transform its look and feel, then post to Messenger — it's that easy. You can even share to Facebook, Twitter, Tumblr and more. It's a new way to see the world.
                    </p>
                </div>
            </div> 
        </div>
    </div> <!-- /container -->