
<?php // var_dump($this->view['user']->user['id']); exit(); ?>
<script>
function accessStatus(id,status)
{
    innerPost( {'id' : id , 'status' : status , 'json':'json'});
}
function OpenWindow(uid ,post)
{
    /* alert(uid +'  '+post); */
    dialog(uid ,post);
}
</script>
<div class="container"  id="id-page-container">
    <div class="jumbotron" style="color:#000000;">
        <div class="row text-center">
            <?php if(!count($this->view['files'])): ?>
                <img src='/public/static/img/cloud.png' />
            <?php endif;?>

            <?php for ($i=0; $i <count($this->view['files']); $i++) : ?> 
            <?php if( $i != 0 && ($i%4)==0 ) : ?>
                </div>
                <div class="row text-center">
            <?php endif?>
                <div class="col-lg-3 col-md-6 hero-feature">
                    <div class="thumbnail">

                        <?php if( strlen($this->view['files'][$i]['cool_search_words']) > 0 ): ?>
                            <img src="/DownloadFiles/<?php echo $this->view['files'][$i]['url']; ?>"  width="223px" height="139px"alt="" />
                        <?php else:?>
                            <img src='/public/static/img/no_foto.gif' width="223px" height="139px"alt="" />
                        <?php endif;?>

                        <div class="caption">
                            <div class="well well-lg">
                                <ul class="list-group">

                                    <li class="list-group-item list-group-item list-group-item-success "><?php echo substr($this->view['files'][$i]['cool_search_words'],0,10); 
                                    echo  strlen($this->view['files'][$i]['cool_search_words']) > 10 ? '...' :''
                                    ?></li>

                                    <li class="list-group-item"><?php echo substr($this->view['files'][$i]['file_description'] , 0, 10);
                                    echo  strlen($this->view['files'][$i]['file_description']) > 10 ? '...' :''
                                    ?></li>
                                    
                                    <li class="list-group-item"><span onclick="OpenWindow('<?php echo (int) $this->view['user']->user['id'];?>','<?php echo $this->view['files'][$i]['id']; ?>')" class="btn btn-primary btn-xs">Open</span></li>
                                    <li class="list-group-item">
                                        <input onclick="accessStatus('<?php echo $this->view['files'][$i]['id']; ?>' , 0)" type="radio" name="access<?php echo $this->view['files'][$i]['id']; ?>" value="0" style=" width: 12px;  height:12px;" <?php 
                                            echo ( $this->view['files'][$i]['access_modifiers'] == 0 ) ? ' checked ' : ' ';
                                        ?> >public
                                        <input onclick="accessStatus('<?php echo $this->view['files'][$i]['id']; ?>' , 1 )" type="radio" name="access<?php echo $this->view['files'][$i]['id']; ?>" value="1" style=" width: 12px;  height:12px;" <?php
                                                echo ( $this->view['files'][$i]['access_modifiers'] == 1 ) ? ' checked ' : ' ';
                                            ?> >private
                                    </li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
            <?php endfor; ?>
        </div>
    </div>
</div>
