
    <div class="container"  id="id-page-container">
        <div class="jumbotron"> 
            <!-- -->
            <!-- Large modal -->
            <button class="btn btn-primary" data-toggle="modal" data-target=".bs-example-modal-lg">Large modal</button>
            <div class="modal fade bs-example-modal-lg" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true">
                <div class="modal-dialog modal-lg">
                    <div class="modal-content">
                        <div style="width: 20px;  height: 550px; padding-top: 50px; padding-left: 50px; color:#000">
                        <p>Download</p>
                        <form action="" method="post">
                            <table>
                                <td>
                                    <div style='padding-left: 40px;'>
                                        <p>file description   <textarea  name="description"  rows="4" cols="50"></textarea></p>
                                        <p>cool search words  <textarea  name="searchWords"  rows="4" cols="50"></textarea></p>
                                        <p><input style="height: 25px; padding: 0 0px;" name="userfile" type="file" /></p>
                                        <p><button type="submit">Sign me in</button></p>
                                    </div>
                                </td>
                                <td style="padding-left: 40px;">
                                    <div><br/><br/>
                                        <input type="radio" name="sex" value="male" style=" width: 42px;  height: 42px;" checked>public<br /><br/>
                                        <input type="radio" name="sex" value="female" style=" width: 42px;  height: 42px;">private<br />
                                    </div>
                                </td>
                            </table>
                        </form>
                        </div>
                    </div>
                </div>
            </div> 
            <!-- --> 
        </div>
    </div> <!-- /container -->